# Generated by Django 3.2.21 on 2023-11-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0002_truckdriver_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='status',
            field=models.CharField(default='Waiting', max_length=200),
        ),
    ]
