# Generated by Django 3.2.21 on 2023-11-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0003_truckdriver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckdriver',
            name='in_progress_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
