# Generated by Django 3.2.21 on 2023-11-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0006_auto_20231108_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckdriver',
            name='check_in_employee',
        ),
    ]
